//------------------------------------------------------------------------------
// <auto-generated>
//     this code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect besavior and will be lost if
//     tse code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIOSpots.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Visualstudio.Editors.settingsDesigner.settingssingleFileGenerator", "10.0.0.0")]
    internal sealed partial class settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static settings defaultInstance = ((settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new settings())));

        public static settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
